### ISSUE TITLE
Feature Request: Press a key for "path" to current element

### ISSUE THREAD

**Issue by klei22** [PaulJuliusMartinez/jless#10]
Just tried jless after seeing on hacker news -- would it be possible to add a way to output the path to a given element?

e.g. 

This would be __super__ helpful when inspecting through highly nested json packets.

**Comment by PaulJuliusMartinez** [comment]
The path to the currently focused node is displayed in the bottom status bar, relative to the input, e.g., `input.foo.bar[2].qux`.

By default it formats object keys using `.key`, unless the key is not a valid JavaScript identifier (matches the regular expression `"^[_$a-zA-Z][_$a-zA-Z0-9]*$`), in which case it renders it as `["key with space"]`. I can imagine a scenario where you always want the `["key"]` syntax, even for valid identifiers. That's probably makes sense for "line" mode (press `m` to see the input as actual JSON).

Is there some functionality you're looking for that's different that that?

You mention deeply nested packets, and the path is truncated when longer than the width of the screen, which, if you need the whole path, is a problem. You _could_ try making your screen wider in that case, but obviously that solution has its limits, and is inconvenient.


I have also considered adding support for copying things to the clipboard, but there are a lot of different things you could want to copy, so I've thought of using two key commands starting with `y` for different things:
- `yy`: copy the current value, pretty printed
- `yo`: copy the current value, pretty printed on one-line
- `yd`: copy the current value, printed as compactly as possible
- `yp`: copy the simplified path to the current node, e.g., `.foo.bar[2].qux`
- `yj`: copy the "pure" path to the current node, e.g., `.["foo"]["bar"][2]["qux"]`
- `yq`: copy a jq style path that includes the current node, e.g., `.foo.bar[].qux`

**Comment by klei22** [comment]
The support for copying to the clipboard sounds fantastic!

**Comment by bew** [comment]
What about the ability to quit the UI and print that path, for consumption by other cli tools?

**Comment by AP2008** [comment]
I added the support for `yy`, `yo`, `yp` and `yj` in this PR: #18 . What should the behaviour be for `yq`. How should `yd` be implemented ?

**Comment by PaulJuliusMartinez** [comment]
Support for copying paths is now available in the [v0.8.0](https://github.com/PaulJuliusMartinez/jless/releases/tag/v0.8.0) release by using `yp` (normal path), `yb` (path but always uses square brackets for object keys) or `yq` (`jq` style path). Copying values can be done with `yy` (pretty printed) or `yv` (not pretty printed), and `yk` copies object keys.
