### ISSUE TITLE
pacman installation command is wrong

### ISSUE THREAD

**Issue by zaidhaan** [PaulJuliusMartinez/jless#111]
The readme writes: `pacman -U jless`, the `-U` flag is for installing packages [downloaded locally](https://wiki.archlinux.org/title/Pacman#Additional_commands).

The [correct way](https://wiki.archlinux.org/title/Pacman#Installing_specific_packages) to install the package would be using the `-S` flag like `pacman -S jless`.

```sh
$ sudo pacman -U jless
loading packages...
error: 'jless': could not find or read package
```
vs
```sh
$ sudo pacman -S jless
resolving dependencies...
looking for conflicting packages...

Packages (1) jless-0.8.0-1

Total Download Size:   0.81 MiB
Total Installed Size:  2.63 MiB

:: Proceed with installation? [Y/n]
```

**Comment by PaulJuliusMartinez** [comment]
Fixed in 0f4691a5d635e52be9ce164878428deee3fcb826 (in `main`) and f18f9bc83ce47e5c8cfedc2b3b82f65f2f0ffbd0 (in `website`, for the website).
