### ISSUE TITLE
CBOR support

### ISSUE THREAD

**Issue by pspacek** [PaulJuliusMartinez/jless#125]
Hello - and first of all thank you for `jless` - it's awesome!

I wonder if you would be open to adding [CBOR format](https://datatracker.ietf.org/doc/html/rfc8949) as input? It is self-descriptive in the same way as JSON is, so I think it would fit nicely into JSON and YAML family.

There are CBOR libraries for Go readily available, e.g. https://pkg.go.dev/github.com/fxamacker/cbor .
Edit: https://github.com/fxamacker/cbor/releases has newer versions as well.

Thank you for considering this.

**Comment by PaulJuliusMartinez** [comment]
I don't believe CBOR is relevant enough to merit inclusion in `jless` at this time. (See [Google Trends](https://trends.google.com/trends/explore?date=today%205-y&geo=US&q=json,yaml,toml,cbor&hl=en))

There seems to be [at least one](https://github.com/fiatjaf/cbor) CBOR-to-JSON tool that you could use together with jless. You could setup the following function in your `.bashrc`:

```bash
# Usage:
# $ cless data.cbor          # Read a file
# $ cat data.cbor | cless    # Read the output of another command
function cless() {
  if [[ $# -eq 0 ]]; then
    cbor | jless
  else
    cbor "$1" | jless
  fi
}
```

**Comment by spacekpe** [comment]
Fair enough, thank you!
