### ISSUE TITLE
open/close children recursively

### ISSUE THREAD

**Issue by llimllib** [PaulJuliusMartinez/jless#127]
Here's an example usage; I'm browsing a package-lock file for a project with a large dependency tree and I want to collapse all the children of the `packages` node so that I can just browse that to scan for packages relevant to a problem I'm having.

In vim, I can do something like `zM` to recursively close all folds, `zo` to open just the packages fold, and all its children are collapsed in just a few keystrokes. (It's actually [moderately a pain](https://stackoverflow.com/questions/21633870/vim-folding-close-all-children-recursively-under-cursor) to close just the child nodes, but that's my ideal motion)

Currrently (as far as I can tell from the manual) there's no way to do "collapse all children of the packages node" - would love to have a shortcut for it.

**Comment by PaulJuliusMartinez** [comment]
`C` and `E` commands, which will deeply collapse and expand a node and all of its siblings, were added in [v0.9.0](https://github.com/PaulJuliusMartinez/jless/releases/tag/v0.9.0).

To close just the child nodes you can either do:
- Hit `j` or `l` to focus the first child, then hit `C`
- Or, if you have multiple top-level elements, you can hit `C` immediately to collapse everything, and then hit `e` to expand all the top level nodes one level

**Comment by llimllib** [comment]
perfect, thanks!
