### ISSUE TITLE
Feature Request: It would be neat to somehow show the legnth of a list element.

### ISSUE THREAD

**Issue by jparsert** [PaulJuliusMartinez/jless#140]
Sometimes a Json file has a list element with thousands of elements. In such cases it is not feasible to scroll all the way down to the end of the list in order to read the last index of the list. It would therefore be neat if it was possible to add the length of the list when the list is closed (i.e. folded).

**Comment by PaulJuliusMartinez** [comment]
Are you running the latest version of jless (0.9.0)? It shows the lengths of lists before the previews:
<img width="341" alt="jless screeshot showing lengths of lists next to array previews" src="https://github.com/PaulJuliusMartinez/jless/assets/3301004/57f39c8f-6187-406d-a92c-d7f982d9ea76">

**Comment by PaulJuliusMartinez** [comment]
Closing because I believe this is now supported, as noted above.
