### ISSUE TITLE
Add an easier way to view long string values

### ISSUE THREAD

**Issue by flxs** [PaulJuliusMartinez/jless#21]
This is neat! One thing though, I tried to use this on JSON data from an API that contains written text in fairly long string values (like a few hundred characters). Inspecting these by scrolling the single truncated line from left to right is very tiring, and there's no way I can find to view these strings in an unescaped form similar to what `jq -r .somestringkey` does (like replace `\n` with actual newlines). I'd love to have a shortcut to expand long strings with newlines into their multiline unescaped representation and be able to read them in a more natural way.

**Comment by ckjoris** [comment]
looks like this is already implemented.

from jless user guide:
`ps` When the currently focused value is a string, copy/print the contents of the string unescaped (except control characters)

**Comment by PaulJuliusMartinez** [comment]
As noted above, `ps` will print the contents of a string, unescaped (and `pp` or `pv` will print out the actual quoted JSON string), which I think suitably addresses this issue.

Word wrap (having longs strings automatically wrap onto multiple lines) would also solve this, and is more explicitly tracked in https://github.com/PaulJuliusMartinez/jless/issues/34.
