### ISSUE TITLE
Distribution using homebrew

### ISSUE THREAD

**Issue by d53dave** [PaulJuliusMartinez/jless#23]
It would be nice to be able to `brew install jless`

**Comment by rolandcrosby** [comment]
I had the same idea and opened homebrew/homebrew-core#95013 to add this.

**Comment by nexxai** [comment]
And it was just merged.  This is awesome.  Thanks Roland!

**Comment by rolandcrosby** [comment]
As @nexxai noted, the Homebrew formula PR got merged and binaries are now available via Homebrew; #28 adds Homebrew instructions to the documentation.

**Comment by thomasmerz** [comment]
@PaulJuliusMartinez - As `jless` is now installable by `brew install jless` this Issue could and should be closed now, am I right? 🤔

**Comment by zachvalenta** [comment]
> @PaulJuliusMartinez - As `jless` is now installable by `brew install jless` this Issue could and should be closed now, am I right? 🤔

Maybe waiting for merge of [this PR](https://github.com/PaulJuliusMartinez/jless/pull/28).

**Comment by thomasmerz** [comment]
No, why? We are already "be able to `brew install jless`" 😉 So the focus of this issue should be solved already.

**Comment by thomasmerz** [comment]
Thanks @d53dave 👍🏻
