### ISSUE TITLE
Support for YAML

### ISSUE THREAD

**Issue by dannyknows** [PaulJuliusMartinez/jless#39]
Support for [YAML](https://yaml.org/) would be great, using the collapse/expand behaviour to traverse large YAML files! 😄

**Comment by gonzaloserrano** [comment]
+1000 😍

**Comment by wbolster** [comment]
piping through [`yq`](https://github.com/mikefarah/yq) first makes this possible today albeit in a slightly less convenient way:

``` shell
< file.yml yq | jless
```

**Comment by PaulJuliusMartinez** [comment]
YAML support has been added in https://github.com/PaulJuliusMartinez/jless/pull/57.

I'll close this when I release a new version with this included.

**Comment by PaulJuliusMartinez** [comment]
This is now available in the [v0.8.0](https://github.com/PaulJuliusMartinez/jless/releases/tag/v0.8.0) release.
