### ISSUE TITLE
Incorrect installation command for Arch linux

### ISSUE THREAD

**Issue by nickspoons** [PaulJuliusMartinez/jless#46]
The installation command in the README for Arch linux is `pacman -U jless`, but jless is not (yet!) in the main arch repositories. The link to the AUR is correct, but the `pacman` command cannot install from the AUR.

Since using tools like `yay`/`aurman` etc. which _do_ install from the AUR are not officially supported by arch, and arch users presumably know how to install from the AUR anyway, I'd recommend just keeping the link, and not giving an installation command, just a message like "Available in the AUR".

Love the tool!

**Comment by PaulJuliusMartinez** [comment]
Thanks for the heads up: Fixed in 8cf15ea0a1e2ab2e4151a183a1125fc596c8371c (README) and 8210adfcc9232aa79003635151f2596b5afd6c92 (website)

**Comment by laktak** [comment]
@PaulJuliusMartinez the link https://aur.archlinux.org/packages/jless is a 404. Did you remove the package?

**Comment by puresick** [comment]
In addition, the command is not quiet right to install directly from Arch Linux repositories.
`pacman -U` installs a package from a file path or an URL.
To install directly from the repositories, `pacman -S` is being used.
