### ISSUE TITLE
mouse conflict with terminal copy

### ISSUE THREAD

**Issue by setop** [PaulJuliusMartinez/jless#50]
Jless is great !

On thing is frustrating to me, I can't manage to copy some text in jless as it seems to take over the mouse.

Is there a way ?

**Comment by maneeshsethi** [comment]
my app crashes on mac osx whenever i click with a mouse. Please let me know if you've found a solution!

**Comment by bryophyta** [comment]
@setop I realise this is a bit late, and I don't know if it covers the use-case you had in mind, but I just thought I'd put this here in case it helps anyone in the future. 

As far as I know you can't copy in jless using the general shortcuts like `cmd+c` / `ctrl+c`. But jless does include a number of shortcuts to copy values (and also paths!) to the clipboard.

From the [user guide](https://jless.io/user-guide.html) (this info can also be accessed from within jless by typing `:help` or pressing `F1`):

> ## Copying
> You can copy various parts of the JSON file to your clipboard using one of the following commands:
> 
> - `yy` Copy the value of the currently focused node, pretty printed
> - `yv` Copy the value of the currently focused node in a "nicely" printed one-line format
> - `yk` Copy the key of the current key/value pair
> - `yp` Copy the path from the root JSON element to the currently focused node, e.g., `.foo[3].bar`
> - `yb` Like `yp`, but always uses the bracket form for object keys, e.g., `["foo"][3]["bar"]`, which is useful if the environment where you'll paste the path doesn't support the .key format, like in Python
> - `yq` Copy a [`jq`](https://stedolan.github.io/jq/) style path that will select the currently focused node, e.g., `.foo[].bar`

**Comment by brewingcode** [comment]
@setop Try holding down alt (⌥) and you'll get your mouse selection back.

**Comment by setop** [comment]
> From the [user guide](https://jless.io/user-guide.html) (this info can also be accessed from within jless by typing `:help` or pressing `F1`):

Read User Guide and In-lined Help ! Shame on me for having skip this step.

> 
> > ## Copying
> > You can copy various parts of the JSON file to your clipboard using one of the following commands:
> > 

Perfect, better than expected.
