### ISSUE TITLE
Arch Linux AUR link in the readme gives a 404 error

### ISSUE THREAD

**Issue by TomSmeets** [PaulJuliusMartinez/jless#52]
The AUR link in the Installation section points to https://aur.archlinux.org/packages/jless but I receive a 404 error page.
The package seems to be removed.

**Comment by grawlinson** [comment]
#53 explains why, hopefully this clears things up. 👍

**Comment by PaulJuliusMartinez** [comment]
Resolved in 212f9b3ac0f37254bc91b7beddb033d41db927f9
