### ISSUE TITLE
jless now available in Arch Linux repositories

### ISSUE THREAD

**Issue by grawlinson** [PaulJuliusMartinez/jless#53]
You can probably revert commit 8cf15ea0a1e2ab2e4151a183a1125fc596c8371c, as I've just added jless to the Arch Linux community repositories. 🎉 

If there are any issues opened relating to Arch Linux, feel free to tag me and I'll try and help out.

**Comment by PaulJuliusMartinez** [comment]
Thank you! I've linked to https://archlinux.org/packages/community/x86_64/jless/ and specified the command `pacman -U jless`. Let me know if I should adjust anything else.
