### ISSUE TITLE
CSI Excapes not handled by termion cause panic

### ISSUE THREAD

**Issue by joelakuhn** [PaulJuliusMartinez/jless#61]
Some valid escape sequences like shift+right (`1;2C`) are not properly parsed by termion and therefore return an `Err` result. This causes a panic in the input loop of `App.run`, which unwraps the `event` variable yielded by the `input` iterator.

**Comment by PaulJuliusMartinez** [comment]
Ah, I think I expected errors like this to be returned using the [`Event::Unsupported`](https://docs.rs/termion/latest/termion/event/enum.Event.html#variant.Unsupported) variant. Evidently not the case.

I've removed the `unwrap` and provided actual error handling in b681708dabb6208cd2c06cba27a6dd02178be5c4. (I should clarify the error prefix from `Error: ` to something like `Input Error: ` or `Error getting user input: ` though... An inadvertent key press may result in a confusing error message. I'll think about it.)

Thanks for the report.
