### ISSUE TITLE
No non-zero exit code in case of parsing errors

### ISSUE THREAD

**Issue by Gerrit-K** [PaulJuliusMartinez/jless#71]
### Description
`jless` currently returns 0 (success) as an exit code, even if the command failed (e.g. if the input wasn't valid JSON). To reproduce:
```bash
jless - <<<"This is no JSON"; echo $?
```
will result the following output:
```
Unable to parse input: "Parse error"
0
```

### Impact / use-case
Having a non-zero exit code increases interoperability and allows for fallbacks in scripts, e.g. `jless "$@" || less "$@"`

**Comment by PaulJuliusMartinez** [comment]
This has been implemented in [`v0.9.0`](https://github.com/PaulJuliusMartinez/jless/releases/tag/v0.9.0).
