### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by skorokithakis** [PaulJuliusMartinez/jless#79]
Hello, thanks for making this! Can you please release one of the versions? Currently they're pre-release, and, as such, some tools and binary managers skip them when considering what to install. What's worse, they aren't even pre-release, as they are the actual versions. The pre-release is meant for things like 0.8.0-rc2, for example, which should legitimately not be upgraded to automatically.

**Comment by PaulJuliusMartinez** [comment]
Done.

**Comment by skorokithakis** [comment]
Thanks, works great!
