### ISSUE TITLE
Make installation easier by providing installation script

### ISSUE THREAD

**Issue by ducaale** [PaulJuliusMartinez/jless#8]
It would be convenient to have a `install.sh` script that downloads the latest binary and places it in the correct directory. Any user would then run the following to install `jless`.
```
curl -sfL https://raw.githubusercontent.com/PaulJuliusMartinez/jless/master/install.sh | sh
````

I think https://github.com/ducaale/xh/blob/master/install.sh could be used as a reference if needed.

**Comment by jfchevrette** [comment]
I mean no disrespect to @ducaale (I use xh and I love it!) but let's not encourage this bad practice further. No one should be blindly running bash scripts downloaded over the internet. Sorry if I'm being harsh but if the author want to have respect for their users safety and security this should not be a recommended way to install the tool

1. Distribution package manager
2. `cargo install jless`
3. https://github.com/PaulJuliusMartinez/jless/releases

To the usual argument of "users should review the script before running it" I would respond that #3 above is both faster, safer and more secure than putting the burden onto the users to review and trust a bash script that does who knows what

**Comment by PaulJuliusMartinez** [comment]
Since I'm kinda new to this whole maintainer role and don't have a ton of experience with distributing software, I'm going to hold off on making it too complicated right now, and stick with just hosting binaries on GitHub and offering jless through standard package managers.
