### ISSUE TITLE
Automate releases with JReleaser

### ISSUE THREAD

**Issue by aalmiray** [PaulJuliusMartinez/jless#82]
https://jreleaser.org may be used to package and distribute Rust binaries to different channels: such as Git releases, Homebrew, macports, Scoop, Snapcraft, etc.

Here are two projects showcasing sample configuration:

https://github.com/manojkarthick/czen
https://github.com/aalmiray/helloworld-rustx

**Comment by PaulJuliusMartinez** [comment]
I will evolve this project's release process as the project matures and the current manual process becomes burdensome.


Independent of the quality of JReleaser, and its relevance to jless's release process, it seems disingenuous to advocate for a tool without disclosing that you are its primary author.
