### ISSUE TITLE
How can I show the items counts of an collapsed object or  array?

### ISSUE THREAD

**Issue by 12lalala** [PaulJuliusMartinez/jless#92]
![image](https://user-images.githubusercontent.com/52209928/172618705-347fb304-80ef-42ae-9f35-b72e5374f1e3.png)

**Comment by alex-unearth** [comment]
#40 can do this! :P

**Comment by brewingcode** [comment]
#40 can do this!  :P

**Comment by 12lalala** [comment]
thanks a lot

**Comment by PaulJuliusMartinez** [comment]
This has been implemented in [`v0.9.0`](https://github.com/PaulJuliusMartinez/jless/releases/tag/v0.9.0).

I'm not totally thrilled with it; it's definitely useful for arrays, but I find it to be less so for objects.
